# Generated by Django 6.0.5 on 2026-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_manufacturer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting registration.', verbose_name='active'),
        ),
    ]
