# Generated by Django 6.0.5 on 2026-05-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_manufacturer_name'),
        ('taxi', '0005_alter_driver_is_active'),
    ]

    operations = [
    ]
